const ADD_CURRENCY = 'ADD_CURRENCY';
const DELETE_CURRENCY = 'DELETE_CURRENCY';
const UPDATE_DATA = 'UPDATE_DATA';

const API_REQUEST = 'API_REQUEST';
const API_SUCCESS = 'API_SUCCESS';
const API_ERROR = 'API_ERROR';

const FETCH_AVAILABLE = 'FETCH_AVAILABLE';

export default {
    ADD_CURRENCY, DELETE_CURRENCY, UPDATE_DATA,
    API_REQUEST, API_SUCCESS, API_ERROR,
    FETCH_AVAILABLE
}
